#!/bin/bash
IN=$1

[ "$1" != "" ] || { echo file not specified; exit -1; }

if [ "$2" != "" ]; then
    OUT=$2;
else
    OUT=`dirname $IN`/`basename $IN .lat`.out
fi;

LLF=`dirname $OUT`/`basename $OUT .out`.ll
BCF=`dirname $OUT`/`basename $OUT .out`.bc

src/latc.pl $IN > $LLF &&
    llvm-as < $LLF > $BCF &&
    llvm-link $BCF lib/runtime.bc -o $OUT && chmod +x $OUT &&
    echo $OUT
