#!/bin/bash

IN=$1
if [ "$2" != "" ]; then
    OUT=$2;
else
    OUT=`dirname $IN`/`basename $IN .lat`.out
fi;

echo $OUT

./latc.pl $IN | llvm-as | llvm-link - lib/runtime.bc -o $OUT &&
    chmod +x $OUT
