#!/bin/bash
IN=$1

[ "$1" != "" ] || { echo file not specified; exit -1; }

if [ "$2" != "" ]; then
    OUT=$2;
else
    OUT=`dirname $IN`/`basename $IN .lat`.out
fi;

echo $OUT

src/latc.pl $IN | llvm-as | llvm-link - lib/runtime.bc -o $OUT &&
    chmod +x $OUT
